### --- Vagrantfile

IMAGE_NAME = "ubuntu/xenial64"

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false
    config.vm.network "forwarded_port", guest:4200, host:4200
    config.vm.network "forwarded_port", guest:8080, host:8080
    config.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.cpus = 2
    end

    config.vm.define "nodejsbox" do |master|
        master.vm.box = IMAGE_NAME
        master.vm.network "private_network", ip: "192.168.2.10"
        master.vm.hostname = "nodejshost"
        master.vm.provision "ansible" do |ansible|
            ansible.playbook = "./ansible-nodejs.yml"
            ansible.extra_vars = {
                node_ip: "192.168.2.10",
            }
        end
    end
end
